trigger:
  branches:
    include:
      - main  # Trigger on push to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout the code
- task: Checkout@1
  displayName: 'Checkout Code'

# Set up Node.js
- task: UseNode@2
  inputs:
    versionSpec: '18.x'  # Use Node.js version 18
  displayName: 'Set up Node.js'

# Install NPM dependencies
- script: |
    npm install
  displayName: 'Install NPM dependencies'

# Build the Angular project
- script: |
    npm run build --prod
  displayName: 'Build Angular project'

# Install Firebase tools
- script: |
    npm install -g firebase-tools
  displayName: 'Install Firebase CLI'

# Deploy to Firebase Hosting
- script: |
    firebase deploy --only hosting --token $(FIREBASE_TOKEN)
  displayName: 'Deploy to Firebase Hosting'
